import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

// GET /api/export/[id] - Export project as Dart files
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const project = await db.project.findUnique({
      where: { id },
    });

    if (!project) {
      return NextResponse.json(
        { error: 'Project not found' },
        { status: 404 }
      );
    }

    // Generate main.dart content
    const mainDart = generateMainDart(project.widgetTree);
    
    // Generate pubspec.yaml content
    const pubspecYaml = generatePubspecYaml(project.name);

    // Create a simple response with the dart code
    // In a real implementation, you would create a ZIP file
    const response = `
================================================================================
Flutter Project: ${project.name}
================================================================================

File: pubspec.yaml
--------------------------------------------------------------------------------
${pubspecYaml}

File: lib/main.dart
--------------------------------------------------------------------------------
${mainDart}

================================================================================
Generated by FlutterForge
================================================================================
`;

    return new NextResponse(response, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${project.name}.txt"`,
      },
    });
  } catch (error) {
    console.error('Error exporting project:', error);
    return NextResponse.json(
      { error: 'Failed to export project' },
      { status: 500 }
    );
  }
}

function generateMainDart(widgetTree: string): string {
  let parsedTree;
  try {
    parsedTree = JSON.parse(widgetTree);
  } catch {
    parsedTree = { type: 'Container', children: [] };
  }

  const widgetCode = generateWidgetCode(parsedTree, 0);

  return `import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return ${widgetCode};
  }
}
`;
}

function generateWidgetCode(node: { type: string; properties: Record<string, unknown>; children: unknown[] }, indent: number): string {
  const spaces = '  '.repeat(indent);
  const innerSpaces = '  '.repeat(indent + 1);

  switch (node.type) {
    case 'Scaffold':
      const bodyCode = node.children && node.children.length > 0 
        ? generateWidgetCode(node.children[0] as Parameters<typeof generateWidgetCode>[0], indent + 1)
        : 'const SizedBox()';
      return `Scaffold(
${innerSpaces}body: ${bodyCode},
${spaces}})`;

    case 'Container':
      const containerProps: string[] = [];
      if (node.properties.width) containerProps.push(`width: ${node.properties.width}`);
      if (node.properties.height) containerProps.push(`height: ${node.properties.height}`);
      if (node.properties.padding) containerProps.push(`padding: EdgeInsets.all(${node.properties.padding})`);
      if (node.properties.color) {
        const colorHex = String(node.properties.color).replace('#', '0xFF');
        containerProps.push(`color: Color(${colorHex})`);
      }
      if (node.properties.borderRadius) {
        containerProps.push(`decoration: BoxDecoration(
${innerSpaces}  borderRadius: BorderRadius.circular(${node.properties.borderRadius}),
${innerSpaces}})`);
      }
      
      const childCode = node.children && node.children.length > 0
        ? generateWidgetCode(node.children[0] as Parameters<typeof generateWidgetCode>[0], indent + 1)
        : null;

      return `Container(
${containerProps.map(p => `${innerSpaces}${p}`).join(',\n')}${childCode ? `,\n${innerSpaces}child: ${childCode}` : ''}
${spaces}})`;

    case 'Row':
    case 'Column':
      const flexProps: string[] = [];
      if (node.properties.mainAxisAlignment) {
        flexProps.push(`mainAxisAlignment: MainAxisAlignment.${node.properties.mainAxisAlignment}`);
      }
      if (node.properties.crossAxisAlignment) {
        flexProps.push(`crossAxisAlignment: CrossAxisAlignment.${node.properties.crossAxisAlignment}`);
      }
      
      const childrenCode = node.children && (node.children as unknown[]).length > 0
        ? (node.children as unknown[]).map((c) => generateWidgetCode(c as Parameters<typeof generateWidgetCode>[0], indent + 2)).join(',\n')
        : '';

      return `${node.type}(
${flexProps.map(p => `${innerSpaces}${p}`).join(',\n')}${flexProps.length > 0 && childrenCode ? ',' : ''}
${childrenCode ? `${innerSpaces}children: [
${childrenCode}
${innerSpaces}]` : ''}
${spaces}})`;

    case 'Text':
      const textProps: string[] = [];
      if (node.properties.fontSize) textProps.push(`fontSize: ${node.properties.fontSize}`);
      if (node.properties.color) {
        const colorHex = String(node.properties.color).replace('#', '0xFF');
        textProps.push(`color: Color(${colorHex})`);
      }
      if (node.properties.fontWeight === 'bold') textProps.push('fontWeight: FontWeight.bold');

      return textProps.length > 0
        ? `Text(
${innerSpaces}'${node.properties.text || 'Text'}',
${innerSpaces}style: TextStyle(
${innerSpaces}  ${textProps.join(',\n  ')}
${innerSpaces}),
${spaces}})`
        : `Text('${node.properties.text || 'Text'}')`;

    case 'ElevatedButton':
      const btnColor = node.properties.color ? `style: ElevatedButton.styleFrom(
${innerSpaces}  backgroundColor: Color(${String(node.properties.color).replace('#', '0xFF')}),
${innerSpaces}),` : '';
      return `ElevatedButton(
${innerSpaces}onPressed: () {},
${btnColor}${btnColor ? '\n' : ''}${innerSpaces}child: Text('${node.properties.label || 'Button'}'),
${spaces}})`;

    case 'OutlinedButton':
      return `OutlinedButton(
${innerSpaces}onPressed: () {},
${innerSpaces}child: Text('${node.properties.label || 'Button'}'),
${spaces}})`;

    case 'TextButton':
      return `TextButton(
${innerSpaces}onPressed: () {},
${innerSpaces}child: Text('${node.properties.label || 'Button'}'),
${spaces}})`;

    case 'TextField':
      return `TextField(
${innerSpaces}decoration: InputDecoration(
${innerSpaces}  labelText: '${node.properties.label || 'Input'}',
${innerSpaces}),
${spaces}})`;

    case 'Image':
      return `Image.network(
${innerSpaces}'${node.properties.src || 'https://via.placeholder.com/150'}',
${innerSpaces}width: ${node.properties.width || 100},
${innerSpaces}height: ${node.properties.height || 100},
${spaces}})`;

    case 'Icon':
      return `Icon(
${innerSpaces}Icons.${node.properties.icon || 'star'},
${innerSpaces}size: ${node.properties.size || 24},
${spaces}})`;

    case 'Card':
      const cardChild = node.children && node.children.length > 0
        ? generateWidgetCode(node.children[0] as Parameters<typeof generateWidgetCode>[0], indent + 1)
        : 'const SizedBox()';
      return `Card(
${innerSpaces}child: ${cardChild},
${spaces}})`;

    case 'SizedBox':
      return `SizedBox(
${node.properties.width ? `${innerSpaces}width: ${node.properties.width},\n` : ''}${node.properties.height ? `${innerSpaces}height: ${node.properties.height},\n` : ''}${spaces}})`;

    default:
      return `const SizedBox()`;
  }
}

function generatePubspecYaml(projectName: string): string {
  return `name: ${projectName.toLowerCase().replace(/\s+/g, '_')}
description: Generated by FlutterForge
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
`;
}
